"""test2

Revision ID: 3ba0f1537bda
Revises: b6fcc46eacee
Create Date: 2025-03-04 07:22:24.540601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '3ba0f1537bda'
down_revision = 'b6fcc46eacee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.drop_table('Passwords')
    op.drop_table('Error_Messages')
    op.drop_table('Refresh_Tokens')
    op.drop_table('Transactions')
    op.drop_table('Access_Tokens')
    op.drop_table('Users')
    op.drop_table('refreshtokens')
    op.drop_table('accesstokens')
    op.drop_table('Security_Questions')
    op.drop_table('Events')
    op.drop_table('Accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('account_no', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('normal_side', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('inital_balance', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('debit', mssql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('credit', mssql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('balance', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('account_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statement', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Account'),
    sa.PrimaryKeyConstraint('account_no', name='PK_Accounts')
    )
    op.create_table('Events',
    sa.Column('event_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('before', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('after', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['Accounts.account_no'], name='Account_Event'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Event'),
    sa.PrimaryKeyConstraint('event_id', name='PK_Events')
    )
    op.create_table('Security_Questions',
    sa.Column('question_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('answer', sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='SecurityQ_User'),
    sa.PrimaryKeyConstraint('question_id', name='PK_Security_Questions')
    )
    op.create_table('accesstokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK__accesstok__user___00DF2177'),
    sa.PrimaryKeyConstraint('token_id', name='PK__accessto__CB3C9E17CFF2C57D')
    )
    op.create_table('refreshtokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK__refreshto__user___03BB8E22'),
    sa.PrimaryKeyConstraint('token_id', name='PK__refresht__CB3C9E17CE3F5F90')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('hire_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('suspend_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('suspend_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name='PK_Users')
    )
    op.create_table('Access_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Access_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Tokens')
    )
    op.create_table('Transactions',
    sa.Column('transaction_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['Accounts.account_no'], name='Account_Transaction'),
    sa.PrimaryKeyConstraint('transaction_id', name='PK_Transactions')
    )
    op.create_table('Refresh_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Refresh_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Refresh_Tokens')
    )
    op.create_table('Error_Messages',
    sa.Column('error_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('error_code', name='PK_Error_Messages')
    )
    op.create_table('Passwords',
    sa.Column('password_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('past_password', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK_Passwords_Users'),
    sa.PrimaryKeyConstraint('password_id', name='PK_Passwords')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61D797F7C4')
    )
    # ### end Alembic commands ###
