"""test1

Revision ID: b6fcc46eacee
Revises: 
Create Date: 2025-03-04 07:04:09.729732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'b6fcc46eacee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('account_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normal_side', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('debit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order', sa.String(length=50), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('account_no')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('before', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['accounts.account_no'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['accounts.account_no'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_table('Transactions')
    op.drop_table('Access_Tokens')
    op.drop_table('Security_Questions')
    op.drop_table('Error_Messages')
    op.drop_table('Events')
    op.drop_table('Refresh_Tokens')
    op.drop_table('Passwords')
    op.drop_table('Accounts')
    op.drop_table('sysdiagrams')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('hire_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mssql.BIT(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mssql.BIT(),
               nullable=False)
        batch_op.alter_column('hire_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61D797F7C4')
    )
    op.create_table('Accounts',
    sa.Column('account_no', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_name', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('normal_side', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('subcategory', sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('inital_balance', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('debit', mssql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('credit', mssql.MONEY(), autoincrement=False, nullable=True),
    sa.Column('balance', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('account_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('statement', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Account'),
    sa.PrimaryKeyConstraint('account_no', name='PK_Accounts')
    )
    op.create_table('Passwords',
    sa.Column('password_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('creation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('past_password', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK_Passwords_Users'),
    sa.PrimaryKeyConstraint('password_id', name='PK_Passwords')
    )
    op.create_table('Refresh_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Refresh_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Refresh_Tokens')
    )
    op.create_table('Events',
    sa.Column('event_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('account_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('before', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.Column('after', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['Accounts.account_no'], name='Account_Event'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Event'),
    sa.PrimaryKeyConstraint('event_id', name='PK_Events')
    )
    op.create_table('Error_Messages',
    sa.Column('error_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('error_code', name='PK_Error_Messages')
    )
    op.create_table('Security_Questions',
    sa.Column('question_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('answer', sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='SecurityQ_User'),
    sa.PrimaryKeyConstraint('question_id', name='PK_Security_Questions')
    )
    op.create_table('Access_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Access_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Tokens')
    )
    op.create_table('Transactions',
    sa.Column('transaction_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('account_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', mssql.MONEY(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_no'], ['Accounts.account_no'], name='Account_Transaction'),
    sa.PrimaryKeyConstraint('transaction_id', name='PK_Transactions')
    )
    op.drop_table('transactions')
    op.drop_table('events')
    op.drop_table('accounts')
    op.drop_table('passwords')
    # ### end Alembic commands ###
