"""syncing

Revision ID: be9c586e173e
Revises: 3ba0f1537bda
Create Date: 2025-03-04 07:39:52.000414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'be9c586e173e'
down_revision = '3ba0f1537bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('Error_Messages')
#     op.drop_table('Access_Tokens')
#     op.drop_table('refreshtokens')
#     op.drop_table('accesstokens')
#     op.drop_table('sysdiagrams')
#     op.drop_table('Refresh_Tokens')
    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_balance', sa.Numeric(precision=18, scale=2), nullable=False))
        batch_op.alter_column('account_name',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('subcategory',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('debit',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('credit',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('statement',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('inital_balance')

    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.alter_column('before',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('after',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Passwords', schema=None) as batch_op:
        batch_op.alter_column('past_password',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('Security_Questions', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('answer',
               existing_type=sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mssql.MONEY(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('Transactions', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=False)

    with op.batch_alter_table('Security_Questions', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.String(length=32),
               type_=sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('question',
               existing_type=sa.String(length=32),
               type_=sa.NCHAR(length=32, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('Passwords', schema=None) as batch_op:
        batch_op.alter_column('past_password',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)

    with op.batch_alter_table('Events', schema=None) as batch_op:
        batch_op.alter_column('after',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=False)
        batch_op.alter_column('before',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=False)

    with op.batch_alter_table('Accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inital_balance', mssql.MONEY(), autoincrement=False, nullable=False))
        batch_op.alter_column('comment',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('statement',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=False)
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=mssql.MONEY(),
               existing_nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('account_name',
               existing_type=sa.String(length=16),
               type_=sa.NCHAR(length=16, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('initial_balance')

    op.create_table('Refresh_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Refresh_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Refresh_Tokens')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61D797F7C4')
    )
    op.create_table('accesstokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK__accesstok__user___00DF2177'),
    sa.PrimaryKeyConstraint('token_id', name='PK__accessto__CB3C9E17CFF2C57D')
    )
    op.create_table('refreshtokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='FK__refreshto__user___03BB8E22'),
    sa.PrimaryKeyConstraint('token_id', name='PK__refresht__CB3C9E17CE3F5F90')
    )
    op.create_table('Access_Tokens',
    sa.Column('token_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.NCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('creation_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('expiry_time', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], name='User_Access_Tokens'),
    sa.PrimaryKeyConstraint('token_id', name='PK_Tokens')
    )
    op.create_table('Error_Messages',
    sa.Column('error_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('error_code', name='PK_Error_Messages')
    )
    # ### end Alembic commands ###
